[package]
name = "emojifinder-core"
version = "0.1.0"
authors = ["Arpad Ray <arraypad@gmail.com>"]
edition = "2018"
license = "MIT"

[dependencies]
failure = "0.1.6"
image = "0.19.0"
lz4 = "1.23.1"
nsvg = "0.5.1"
rmp-serde = "0.14.0"
serde = "1.0.102"
serde_derive = "1.0.102"
trigram = "0.4.4"
