[package]
name = "emojifinder-builder"
version = "0.1.0"
authors = ["Arpad Ray <arraypad@gmail.com>"]
edition = "2018"
license = "MIT"

[dependencies]
env_logger = "0.7.1"
failure = "0.1.6"
log = "0.4.0"
emojifinder-index = { path = "../index" }
